In [5]:
import jovian

In [6]:
import numpy as np

In [7]:
kanto = np.array([73,67,43])

In [8]:
kanto

array([73, 67, 43])

In [9]:
w1,w2,w3 = 0.3,0.2,0.5
weights = np.array([w1,w2,w3])

In [10]:
weights

array([0.3, 0.2, 0.5])

In [11]:
type(kanto)

numpy.ndarray

In [12]:
type(weights)

numpy.ndarray

In [13]:
np.dot(kanto,weights)

56.8

In [14]:
kanto*weights

array([21.9, 13.4, 21.5])

In [15]:
(kanto*weights).sum()

56.8

In [16]:
#python lists
arr1 = list(range(100000))
arr2 = list(range(100000,200000))

#Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [17]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: total: 15.6 ms
Wall time: 14 ms


833323333350000

In [18]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


893678192

In [19]:
climate_data = np.array([
    [73,67,43],
    [91,88,74],
    [87,134,58],
    [102,43,37],
    [69,96,70]
    ]
)
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  74],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [20]:
#2D array matrix
climate_data.shape

(5, 3)

In [21]:
#1D vector
weights.shape

(3,)

In [22]:
arr3 = np.array([
    [[11,12,13],
    [13,14,15]],

    [[15,16,17],
    [17,18,19.5]]
])

In [23]:
arr3.shape

(2, 2, 3)

In [24]:
weights.dtype

dtype('float64')

In [25]:
climate_data.dtype

dtype('int32')

In [26]:
np.matmul(climate_data,weights)

array([56.8, 81.9, 81.9, 57.7, 74.9])

In [27]:
climate_data @ weights

array([56.8, 81.9, 81.9, 57.7, 74.9])

In [28]:
import urllib.request

In [29]:
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt'
)

('climate.txt', <http.client.HTTPMessage at 0x248d7645930>)

In [30]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [31]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [32]:
climate_data.shape

(10000, 3)

In [33]:
weights

array([0.3, 0.2, 0.5])

In [34]:
yields = climate_data @ weights

In [35]:
yields.shape

(10000,)

In [36]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [37]:
np.savetxt(
    'climate_results.txt',
    climate_results,
    fmt='%.2f',
    header='temperature,rainfall,humidity,yield_apples',
    comments=''
)

In [38]:
arr2 = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,1,2,3]
    ]
)

In [39]:
arr3 = np.array(
    [
        [11,12,13,14],
        [15,16,17,18],
        [19,11,12,13]
    ]
)

In [40]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [41]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [42]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [44]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [45]:
arr2.shape

(3, 4)

In [46]:
arr4 = np.array([4,5,6,7])

In [47]:
arr4.shape

(4,)

In [48]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [51]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,5]])

In [52]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [53]:
(arr1 == arr2).dtype

dtype('bool')

In [54]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [55]:
(arr1 == arr2).sum()

3

In [57]:
arr3 = np.array([
    [[11,12,13,14],[13,14,15,19]],
    [[15,16,17,21],[63,92,36,18]],
    [[98,32,81,23],[17,18,19.5,43]]
])

In [58]:
arr3.shape

(3, 2, 4)

In [59]:
#Single element
arr3[1,1,2]

36.0

In [60]:
#Subarray using ranges
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [61]:
#Mixing indices and ranges
arr3[1:,1,3]

array([18., 43.])

In [62]:
#Mixing indices and ranges
arr3[1:,1,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [63]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [64]:
#All zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [65]:
#All ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
#Random vector
np.random.rand(5)

array([0.15907847, 0.52827019, 0.43703547, 0.53207537, 0.00645405])

In [69]:
#Random matrix
np.random.randn(2,3) #rand vs randn - what's the difference?

array([[ 0.00866668,  0.32957732,  0.25110433],
       [ 1.32570493, -1.99471585,  0.51608721]])

In [70]:
#Fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [72]:
#Range with start
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [74]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [73]:
#Equally spaced numbers in a range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [75]:
#Equally spaced numbers in a range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [76]:
np.linspace(3,27,18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])

In [77]:
import jovian
jovian.commit(filename='analysis1.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "pranshul-hatwar/python-pranshul" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/pranshul-hatwar/python-pranshul


'https://jovian.ai/pranshul-hatwar/python-pranshul'

In [85]:
np.__version__

'1.24.1'

In [87]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

In [88]:
arr_null = np.zeros(10)
arr_null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
arr_null.size

10

In [90]:
arr_null.itemsize

8

In [91]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [92]:
arr5 = np.arange(10,50,1)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [93]:
arr5_reverse = np.flip(arr5)
arr5_reverse

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [95]:
arr6 = np.arange(0,9,1).reshape((3,3))
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
np.random.rand(3,3,3)

array([[[0.33586106, 0.10505795, 0.71719056],
        [0.83197636, 0.21862378, 0.4574005 ],
        [0.26626073, 0.89015188, 0.89363431]],

       [[0.29635052, 0.89812256, 0.10973884],
        [0.66215997, 0.39431536, 0.73549892],
        [0.46310031, 0.27713077, 0.70483427]],

       [[0.0986462 , 0.18118542, 0.63382327],
        [0.03062794, 0.05097405, 0.06580579],
        [0.10940465, 0.00880084, 0.94758044]]])

In [106]:
arr7 = np.random.rand(10,10)
arr7

array([[0.2416543 , 0.68773626, 0.92612613, 0.93139905, 0.53890081,
        0.81397865, 0.53420652, 0.90599975, 0.85608491, 0.26356539],
       [0.29164316, 0.0961318 , 0.08408946, 0.50236044, 0.63873064,
        0.00930549, 0.91548681, 0.85636308, 0.41094192, 0.27024759],
       [0.6264338 , 0.97450765, 0.77714255, 0.35423307, 0.31046748,
        0.3891788 , 0.77425537, 0.81282824, 0.41192103, 0.55278132],
       [0.17443841, 0.24932077, 0.02365293, 0.49136269, 0.54602813,
        0.75862123, 0.68051472, 0.74702417, 0.24987245, 0.05250646],
       [0.22172883, 0.78953595, 0.15407721, 0.83928751, 0.29613972,
        0.46881985, 0.7086613 , 0.84384507, 0.44225465, 0.89226435],
       [0.42495257, 0.65015659, 0.45486854, 0.49855684, 0.24735664,
        0.39290936, 0.72355834, 0.63963246, 0.40462756, 0.97696157],
       [0.91815247, 0.54412469, 0.97538465, 0.23338831, 0.11613767,
        0.19747687, 0.34146181, 0.44359789, 0.64281223, 0.98477635],
       [0.56831843, 0.24270435, 0.7054428

In [105]:
max_arr7 = np.max(arr7)
max_arr7

0.9789057650406646

In [108]:
arr8 = np.random.rand(30)
arr8

array([0.77368065, 0.10015778, 0.87397891, 0.28455209, 0.15851136,
       0.92878103, 0.24014872, 0.37269925, 0.03196946, 0.93535094,
       0.59076966, 0.15912427, 0.26353737, 0.3777754 , 0.79431244,
       0.54195684, 0.24942696, 0.74049026, 0.65942566, 0.29001468,
       0.0816488 , 0.6711805 , 0.49963942, 0.56605815, 0.06432604,
       0.74264157, 0.63765675, 0.38079942, 0.55485403, 0.31461889])

In [112]:
np.mean(arr8)

0.4626695763344504

In [114]:
arr9 = np.ones((5,5))
arr9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
arr9[1:-1,1:-1] = 0
arr9

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [117]:
np.nan * 0

nan

In [118]:
np.nan == np.nan

False

In [119]:
np.inf > np.nan

False

In [120]:
np.nan - np.nan

nan

In [121]:
np.nan in set([np.nan])

True

In [122]:
0.3 == 3*0.1

False